version: "3.1"
services:
    db_mysql:
        image: mysql:latest
        environment:
          - MYSQL_ROOT_PASSWORD=hejsan123
          - MYSQL_DATABASE=productinformation
          - MYSQL_PASSWORD=hejsan123
        ports:
          - "3306:3306"
        expose: 
          - "3306"

    nginx:
        container_name: some-nginx
        image: nginx:latest
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app

    app:
        restart: on-failure
        depends_on:
            - db_mysql
        environment:
            #- DATABASE_HOST=db_mysql
            #- DATABASE_USER=root
            #- DATABASE_PASSWORD=hejsan123
            #- DATABASE_NAME=databasen
            #- DATABASE_PORT=3306
            SPRING_DATASOURCE_URL: jdbc:mysql://db_mysql:3306/productinformation
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: hejsan123
        build: .
        ports:
            - 8080:8080
        expose:
            - "8080"



